# Generated by Django 4.0.3 on 2022-11-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='landing_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True)),
                ('h1', models.CharField(blank=True, max_length=100)),
                ('h2', models.CharField(blank=True, max_length=100)),
                ('p', models.CharField(blank=True, max_length=500)),
                ('img', models.TextField(blank=True)),
                ('read_link', models.TextField(blank=True)),
                ('yt_link', models.TextField(blank=True)),
                ('file_link', models.TextField(blank=True)),
                ('yt_title', models.CharField(blank=True, max_length=100)),
                ('file_title', models.CharField(blank=True, max_length=100)),
                ('layout', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
