# Generated by Django 4.0.3 on 2022-11-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_alter_landing_page_file_title_alter_landing_page_h1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='jeeyar_parampara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ponnadikkal_jeeyar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='thaniyans_and_vazhi_thirunamams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='vanamamalai_education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='vanamamalai_mutt_branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='vanamamalai_other_temple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='vanamamalai_temple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.TextField()),
                ('banner_heading', models.TextField()),
                ('content_title', models.TextField()),
                ('content_subtitle', models.TextField()),
                ('content_image', models.TextField()),
                ('tab1_heading', models.TextField()),
                ('tab1_desc', models.TextField()),
                ('tab2_heading', models.TextField()),
                ('tab2_desc', models.TextField()),
                ('tab3_heading', models.TextField()),
                ('tab3_desc', models.TextField()),
                ('tab4_heading', models.TextField()),
                ('tab4_desc', models.TextField()),
            ],
        ),
    ]
